version: '3'
services:
  api-yp-fintech:
    image: node:latest    
    container_name: api-yp-fintech
    restart: always
    env_file:
     - .env    
    ports:
      - "3000:3000"     
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app      
    command: npm start      