version: '3'
services:   
  api-yp-fintech:
    container_name: api-yp-fintech
    build: .
    image: api-yp-fintech
    restart: always
    volumes:
      - ./dist:/usr/src/app/dist
    ports:
      - "3000:3000"      
    command: npm start
