version: '3'
services:   
  api-yp-fintech:
    container_name: api-yp-fintech
    build: .
    image: api-yp-fintech
    restart: always
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
      - ./.env:/usr/src/app/.env
    ports:
      - "3000:3000" 
      - "9222:9222"     
    command: npm run debug-container
